yarnPath: .yarn/releases/yarn-3.5.0.cjs

nodeLinker: pnp

packageExtensions:
  '@storybook/cli@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@storybook/core-server@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  'storybook@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@storybook/core-common@^7':
    dependencies:
      '@storybook/react-webpack5': '*'
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@storybook/builder-manager@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
      vfile: '*'
  'vfile@*':
    dependencies:
      url: '*'
      path: '*'
  '@storybook/core-webpack@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@storybook/docs-tools@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  '@storybook/telemetry@*':
    peerDependencies:
      react: '*'
      react-dom: '*'
  'eslint-config-react-app@*':
    peerDependencies:
      '@babel/plugin-syntax-flow': '*'
      '@babel/plugin-transform-react-jsx': '*'
  'react-scripts@*':
    peerDependencies:
      '@babel/plugin-syntax-flow': '*'
      '@babel/plugin-transform-react-jsx': '*'
  '@storybook/preset-create-react-app@*':
    peerDependencies:
      react-refresh: '*'
      typescript: '*'
      webpack: '*'

      
supportedArchitectures:
  cpu:
    - x64
    - arm64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux